Pull request to add some code requirements
lfmnovaes/Hello-Microverse pull request #1
Opened 2021-08-10 21:16 UTC by lfmnovaes

Following step-by-step requirements described here: https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/hello_microverse_project.md

2021-08-10 21:42 UTC, barackm requested changes
Hi @lfmnovaes , 👋 

You have done an amazing job so far! 👏👏👏
However, there are some issues that you still need to work on to go to the next project. But remember you are almost there 😉  😉 !

## To highlight

✔️   You have a very descriptive README
✔️   You have descriptive commit messages 
✔️   You have a descriptive PR title

# STATUS: Required Changes ♻️
### _Check the comments under the review._ 👇 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 21:42 UTC, barackm commented on .github/workflows/linters.yml
> +name: Linters
- [ ] It's a good thing that you have added the linter to your project, But it seems that the tests to check for linter errors are not running yet. Please let's follow the instructions described [here](https://github.com/microverseinc/linters-config/tree/master/html-css) on how to set up the linter correctly.

2021-08-10 21:55 UTC, lfmnovaes commented on .github/workflows/linters.yml
> +name: Linters
I noticed that, but since GitHub is still experiencing major outage on GitHub Actions. I didn't know if it's me or the website. Can check live through [here](https://www.githubstatus.com/).
But still, I've checked with the Linters locally and my project passed all.

2021-08-10 22:27 UTC, barackm commented on .github/workflows/linters.yml
> +name: Linters
Hi @ifmnovaes, Sorry for that, it seems that GitHub is facing an issue with GitHub action. So kindly request another review and the GitHub actions issue will be ignored.

2021-08-10 23:10 UTC, lfmnovaes commented on .github/workflows/linters.yml
> +name: Linters
Through the dashboard?

2021-08-11 00:05 UTC, barackm commented on .github/workflows/linters.yml
> +name: Linters
Yes please!

2021-08-11 00:32 UTC, lfmnovaes commented on .github/workflows/linters.yml
> +name: Linters
Ok done. Tried to explain everything in it too.

2021-08-11 01:24 UTC, DanteAlonsoHT requested changes
<h1>Status: Changes Required 🚫 ♻️  </h1>

Hi @lfmnovaes, 

Great work on making this project 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

_Check the comments under the review._

<hr>

Cheers and Happy coding, I know you have the capabilities enough to fix these changes required in time!👏😉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-08-11 01:24 UTC, DanteAlonsoHT commented on README.md
> +
You can remove  The "**Run Tests**" and "**Deployment**" sections due to you only use them when you are using unit testing or integration testing in your projects or if you deployed your app to a hosting.

- [ ]  Remove the **Run Tests** and **Deployment** section in your README file.

2021-08-11 01:24 UTC, DanteAlonsoHT commented on README.md
> +
For this project, it's not necessary having the install section, I know you did a huge effort to make a descriptive README file, and it looks good, but in this particular project, you should remove some unnecessary sections.

- [ ] Remove install section from your README file.

2021-08-11 01:24 UTC, DanteAlonsoHT commented on README.md
> +[Live Demo Link](https://lfmnovaes.github.io/Hello-Microverse/) (Not online yet)
Remove the Live Demo section because your link is not working, also for the requirements is not necessary, you can remove it 😉 

- [ ] Remove the Live Demo section or if you want to deploy your app using Github pages, feel free to do that, it would be amazing although it's not mandatory for this project.

2021-08-11 01:24 UTC, DanteAlonsoHT commented on README.md
>  ![screenshot](./app_screenshot.png)
You can remove this image or adding the right image because it doesn't show how your project looks like.

- [ ] Remove image from your README file.

2021-08-11 01:34 UTC, lfmnovaes commented on README.md
>  ![screenshot](./app_screenshot.png)
Gonna choose to remove it cause looks pretty basic at this moment.

2021-08-11 02:12 UTC, lfmnovaes commented on README.md
>  ![screenshot](./app_screenshot.png)
I've followed your advice and changed accordingly. Do I need to submit it again into the dashboard?

2021-08-11 19:12 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED ✔🎉✔**
Hello @lfmnovaes 👋🏽
I know you were scared but now you can relax because you did it 🎉👏🏽👏🏽. Your project is now complete and ready to be merged.

 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 19:18 UTC, merged